### ISSUE TITLE
How to add dynamic values

### ISSUE THREAD

**Issue by ashishparmar** [siralam/DropDownView#1]
Hello
This is a nice library but I want to add custom POJO class (getter-setter method).

**Comment by siralam** [comment]
May you clarify your question? Do you mean you want to use your own POJO class, instead of `String`, as selectable items?

**Comment by ashishparmar** [comment]
Yes i would like to add custom POJO class

**Comment by siralam** [comment]
I think I would not consider adding this feature. To `DropDownView`, what it cares is only the name of the selectable items. So I would suggest you generate another `List<String>` from your own POJO list and pass it into `DropDownView`.

**Comment by kelvinmakau444** [comment]
@siralam , this a nice library, good job. However, what if i want to use custom adapter i.e with a list having an icon and a description.

**Comment by Aasis007** [comment]
how do set the values to the dropdownlist from an API ?
