### ISSUE TITLE
DrowDownList goes behind the button

### ISSUE THREAD

**Issue by ZakariaJawas** [siralam/DropDownView#10]
When i open the list and it is too long that some options must be above the views below it, if there is a Button, it covers some options.
There is no problem with other views like TextViews

**Comment by siralam** [comment]
May be can you post some screencaps or a short video clip? I can't get what you mean.

**Comment by ZakariaJawas** [comment]
I managed to solve the problem by hiding the button when the list is open
The main issue is the list is always behind the button i think it is a matter of elevation

**Comment by siralam** [comment]
Yes if you have a button which has an elevation, you probably need to make the dropdown has an elevation higher than the button.
