### ISSUE TITLE
when list excced screen space the dropdown view is sliced

### ISSUE THREAD

**Issue by unix14** [siralam/DropDownView#11]
view is sliced if array of string exceed certain number

![image](https://user-images.githubusercontent.com/19227232/70731874-23787300-1d10-11ea-95fc-904ec4bd092d.png)

**Comment by siralam** [comment]
Can't you scroll? It is supposed to be scrollable.

**Comment by siralam** [comment]
Oops. Just found that it is not scrollable, my bad.

**Comment by siralam** [comment]
I would merge this into #12.
