### ISSUE TITLE
Can I set the arrow always align to the parent right?

### ISSUE THREAD

**Issue by mt73564** [siralam/DropDownView#6]
Can I set the arrow always align to the parent right? because currently, the arrow keep stick to the right of the content

**Comment by siralam** [comment]
That's a valid requirement. Let me add it in the next version!

**Comment by Shailevy** [comment]
I also need this,  any updates ? :)

**Comment by fc9734ygn** [comment]
Maybe it would also be possible to align the text to the start and arrow to the end?

**Comment by siralam** [comment]
Allowed aligning arrow to the end in v1.1.0.

As for aligning text to the left... I will add that in the next version if one more people request it
