### ISSUE TITLE
How to deselect dropdown !

### ISSUE THREAD

**Issue by mahmooddaqa** [siralam/DropDownView#8]
How to deselect dropdown !

**Comment by siralam** [comment]
By design you can only select another item 😛

**Comment by mahmooddaqa** [comment]
Also can't by code ! @siralam

**Comment by siralam** [comment]
By design means it is designed this way, not by the "design view" of Android Studio...

**Comment by mahmooddaqa** [comment]
i feel you mean that

**Comment by mahmooddaqa** [comment]
Also 
setPlaceholderText("");

Not Working 
@siralam

**Comment by siralam** [comment]
De-selection is implemented in v1.1.0. Please refer to the updated README.

As for `setPlaceholderText("")` not working, I found that most programmatic methods are not working...
By the time I made this library I misunderstood the usage of `invalidate()` and `requestLayout()`, so to fix this would be quite a bit of work; I will make that to the next version.
